### ISSUE TITLE
Arreglen su .gitignore para que no tengan tanta basura en su codigo

### ISSUE THREAD

**Issue by joperezr** [EstefaniaMoralesA/VendeAgroWeb#1]
Hola @EstefaniaMoralesA @SantiFdezM, estaba checando su proyecto y me di cuenta de que tienen muchas cosas checkin-eadas que no deberian de estar, como por ejemplo todos los folders de `.vs` o el folder de `packages` o incluso hasta `bin`. La manera de arreglarlo es cambiando su .gitignore para que en primera este en el root de su repo, y no un directorio abajo, y luego cambiar los contenidos para que sean como [este .gitignore](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore)

**Comment by EstefaniaMoralesA** [comment]
Gracias amigo Joe!
